vars: {
  d2-config: {
    theme-overrides: {
      B1: "#e53834"
      B2: "#c1121f"
      B3: "#2ab6f6"
      B4: "#0e141c"
      B5: "#5f6368"
      B6: "#f8f9fa"

      AA2: "#e53834"
      AA4: "#c1121f"
      AA5: "#2ab6f6"

      AB4: "#0e141c"
      AB5: "#5f6368"

      N1: "#0e141c"
      N2: "#1a1a1a"
      N3: "#5f6368"
      N4: "#e8eaed"
      N5: "#e8eaed"
      N6: "#f8f9fa"
      N7: "#ffffff"
    }
  }
}
